use_frameworks!
platform :ios, '8.0'

target 'KDCalenderPicker_Example' do
  pod 'KDCalenderPicker', :path => '../'

  target 'KDCalenderPicker_Tests' do
    inherit! :search_paths

    pod 'Quick'
    pod 'Nimble'
    pod 'FBSnapshotTestCase'
    pod 'Nimble-Snapshots' 
  end
end
